apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        env: 
        - name: PODINFO_UI_COLOR
          value: "#76577c"
        - name: PODINFO_UI_MESSAGE
          value: "UI testing by MB"
        - name: PODINFO_CACHE_SERVER
          value: "http://redis-leader.default.svc.cluster.local:6379"

---

apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  ports:
  - port: 9898
    targetPort: 9898
  selector:
    app: podinfo

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50